name: Despliegue App Mobile

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v2     

     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
         node-version: '16'          

     - name: Install dependencies
       run: npm install
        # Construir la aplicación Ionic
     - name: Build Ionic app
       run: npm run build

      # Instalar Capacitor y sincronizar Android
     - name: Sync Capacitor Android
       run: |
         npx cap sync android

      # Configurar JDK y Android SDK
     - name: Setup Android environment
       uses: android-actions/setup-android@v2
       with:
        api-level: 33
         build-tools: 33.0.2

      # Construir el APK
     - name: Build APK
        run: |
         cd android
         ./gradlew assembleRelease

      # Guardar el APK como artefacto
     - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
         name: app-release.apk
         path: android/app/build/outputs/apk/release/app-release.apk

         


    